--
-- PostgreSQL database dump
--

-- Dumped from database version 12.2
-- Dumped by pg_dump version 12.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.basic_open_id_user DROP CONSTRAINT IF EXISTS fksnij07d270655i3abkyl6cpf9;
ALTER TABLE IF EXISTS ONLY public.message DROP CONSTRAINT IF EXISTS fkrkuv2htexgc114vw6cljjgmco;
ALTER TABLE IF EXISTS ONLY public.chats DROP CONSTRAINT IF EXISTS fkc375bx9vqq8tlcjmugdlmlhq1;
ALTER TABLE IF EXISTS ONLY public.chats DROP CONSTRAINT IF EXISTS fk53cb322xq1ow3w6o4baag5qge;
DROP INDEX IF EXISTS public.idx_user_email;
ALTER TABLE IF EXISTS ONLY public.account DROP CONSTRAINT IF EXISTS uk_q0uja26qgu1atulenwup9rxyr;
ALTER TABLE IF EXISTS ONLY public.technical_info DROP CONSTRAINT IF EXISTS technical_info_pkey;
ALTER TABLE IF EXISTS ONLY public.message DROP CONSTRAINT IF EXISTS message_pkey;
ALTER TABLE IF EXISTS ONLY public.chats DROP CONSTRAINT IF EXISTS chats_pkey;
ALTER TABLE IF EXISTS ONLY public.basic_open_id_user DROP CONSTRAINT IF EXISTS basic_open_id_user_pkey;
ALTER TABLE IF EXISTS ONLY public.account DROP CONSTRAINT IF EXISTS account_pkey;
DROP TABLE IF EXISTS public.technical_info;
DROP VIEW IF EXISTS public.messagestatisticview;
DROP TABLE IF EXISTS public.message;
DROP TABLE IF EXISTS public.chats;
DROP TABLE IF EXISTS public.basic_open_id_user;
DROP TABLE IF EXISTS public.account;
DROP SCHEMA IF EXISTS public;
--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS public.account (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    nickname character varying(255),
    password character varying(255) NOT NULL,
    phone character varying(255),
    role character varying(255),
    state character varying(255)
);


ALTER TABLE public.account OWNER TO postgres;

--
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: basic_open_id_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS public.basic_open_id_user (
    name character varying(255) NOT NULL,
    email character varying(255),
    nickname character varying(255),
    id bigint NOT NULL
);


ALTER TABLE public.basic_open_id_user OWNER TO postgres;

--
-- Name: chats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS public.chats (
    id_to bigint NOT NULL,
    id_from bigint NOT NULL,
    state character varying(255)
);


ALTER TABLE public.chats OWNER TO postgres;

--
-- Name: message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS public.message (
    id_pk bigint NOT NULL,
    id_from bigint,
    id_to bigint,
    message character varying(255),
    message_status character varying(255),
    "time" timestamp without time zone
);


ALTER TABLE public.message OWNER TO postgres;

--
-- Name: message_id_pk_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.message ALTER COLUMN id_pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_id_pk_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messagestatisticview; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW  public.messagestatisticview AS
 SELECT message.id_from,
    count(message.message) AS count
   FROM public.message
  GROUP BY message.id_from
  ORDER BY (count(message.message));


ALTER TABLE public.messagestatisticview OWNER TO postgres;

--
-- Name: technical_info; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS  public.technical_info (
    id bigint NOT NULL,
    confirm_state character varying(255),
    isdeleted boolean NOT NULL,
    uuid uuid
);


ALTER TABLE public.technical_info OWNER TO postgres;

--
-- Name: technical_info_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.technical_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.technical_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Name: account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.account_id_seq', 7, true);


--
-- Name: message_id_pk_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.message_id_pk_seq', 61, true);


--
-- Name: technical_info_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.technical_info_id_seq', 7, true);


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- Name: basic_open_id_user basic_open_id_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.basic_open_id_user
    ADD CONSTRAINT basic_open_id_user_pkey PRIMARY KEY (name);


--
-- Name: chats chats_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT chats_pkey PRIMARY KEY (id_to, id_from);


--
-- Name: message message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT message_pkey PRIMARY KEY (id_pk);


--
-- Name: technical_info technical_info_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.technical_info
    ADD CONSTRAINT technical_info_pkey PRIMARY KEY (id);


--
-- Name: account uk_q0uja26qgu1atulenwup9rxyr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT uk_q0uja26qgu1atulenwup9rxyr UNIQUE (email);


--
-- Name: idx_user_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_email ON public.account USING btree (email);


--
-- Name: chats fk53cb322xq1ow3w6o4baag5qge; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT fk53cb322xq1ow3w6o4baag5qge FOREIGN KEY (id_to) REFERENCES public.account(id);


--
-- Name: chats fkc375bx9vqq8tlcjmugdlmlhq1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT fkc375bx9vqq8tlcjmugdlmlhq1 FOREIGN KEY (id_from) REFERENCES public.account(id);


--
-- Name: message fkrkuv2htexgc114vw6cljjgmco; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT fkrkuv2htexgc114vw6cljjgmco FOREIGN KEY (id_from) REFERENCES public.account(id);


--
-- Name: basic_open_id_user fksnij07d270655i3abkyl6cpf9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.basic_open_id_user
    ADD CONSTRAINT fksnij07d270655i3abkyl6cpf9 FOREIGN KEY (id) REFERENCES public.account(id);


--
-- PostgreSQL database dump complete
--

